create table clean.dummies (
    encId int null
    , readmitted int null
    , ipEnc int null
    , edEnc int null
    , metformin int null
    , dmRx int null
    , dx2 int null
    , dx5 int null
    , dx6 int null
    , dx7 int null
    , dx8 int null
    , raceC int null
    , raceA int null
    , dischHome int null
    , dischTrans int null
    , admitEmerg int null
    , admitOther int null
    , admitPcp int null
    , admitSurg int null
    , age040 int null
    , age4050 int null
    , age5060 int null
    , age6070 int null
    , age7080 int null
    , age8090 int null
    , age90100 int null
    , raceAage040 int null
    , raceAage4050 int null
    , raceAage5060 int null
    , raceAage6070 int null
    , raceAage7080 int null
    , raceAage8090 int null
    , raceAage90100 int null
    , raceCage040 int null
    , raceCage4050 int null
    , raceCage5060 int null
    , raceCage6070 int null
    , raceCage7080 int null
    , raceCage8090 int null
    , raceCage90100 int null
    , discHomeAge040 int null
    , discHomeAge4050 int null
    , discHomeAge5060 int null
    , discHomeAge6070 int null
    , discHomeAge7080 int null
    , discHomeAge8090 int null
    , discHomeAge90100 int null
    , discTransAge040 int null
    , discTransAge4050 int null
    , discTransAge5060 int null
    , discTransAge6070 int null
    , discTransAge7080 int null
    , discTransAge8090 int null
    , discTransAge90100 int null
    , discHomeAdmitEmerg int null
    , discHomeAdmitOther int null
    , discHomeAdmitPcp int null
    , discHomeAdmitSurg int null
    , discTransAdmitEmerg int null
    , discTransAdmitOther int null
    , discTransAdmitPcp int null
    , discTransAdmitSurg int null
)